package com.encycbrit.rest.model;

public enum BritannicaTopicsTemplate {

    ANY;


    public final static String  CACHE =
        new StringBuilder(5_000).
        append("</br><html><ul style='list-style: none;'>").
        append("</br><li>&lt;publish-list&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;4144&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;acrobatic-skiing-Year-In-Review-1997&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;sports&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;4143&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;acrobatic-skiing&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;sports&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;3118&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;ace-sports&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;sports&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1376&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;ablation-cluster-preparation&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;science&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1378&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;ablation-glaciation&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;science&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1383&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;ablation-layer&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;science&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1372&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;abl&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;plant&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;331&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;abaca&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;plant&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;304&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Aarons-beard&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;plant&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;2565&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Acacian-Schism&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;event&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1427&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Treaty-of-Abo&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;event&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1393&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Ableman-v-Booth&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;event&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1015&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Abel-biblical-figure&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;biography&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1007&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Zainul-Abedin&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;biography&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1010&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Richard-Wilhelm-Heinrich-Abegg&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;biography&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1004&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;abecedarius&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;art&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;323&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;ab-ovo&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;art&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;324&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Aba-Nigeria&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;place&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;263&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Aare-River&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;place&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;265&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Emil-Aarestrup&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;biography&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;253&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;aardvark&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;animal&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;257&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;aardwolf&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;animal&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;261&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Aare-Massif&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;place&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;1&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;A-poem-by-Zukofsky&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;topic&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;6&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;Operation-A&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;topic&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;8&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;A-1-aircraft&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;technology&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>            &lt;topicid&gt;11&lt;/topicid&gt;").
        append("</br><li>            &lt;urltitlegt;A-1-Soviet-launch-vehicle&lt;/urltitle&gt;").
        append("</br><li>            &lt;urlclass&gt;topic&lt;/urlclass&gt;").
        append("</br><li>        &lt;url-publish&gt;").
        append("</br><li>    &lt;/publish-list&gt;").toString();
}
